// Build-time LLM mission summaries, loaded as raw markdown strings.
//
// The .md files are generated by scripts/generate_summaries.ts (Anthropic SDK,
// build-time only) and committed. This loader resolves them eagerly at bundle
// time — zero runtime API calls. If a summary file does not exist yet, the
// loader returns null and the card shows a graceful placeholder.

const modules = import.meta.glob('./missions/summaries/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const bySlug: Record<string, string> = {}
for (const [path, content] of Object.entries(modules)) {
  const slug = path.split('/').pop()?.replace(/\.md$/, '')
  if (slug) bySlug[slug] = stripFrontmatter(content)
}

function stripFrontmatter(md: string): string {
  // Remove a leading YAML frontmatter block (--- … ---) if present.
  if (md.startsWith('---')) {
    const end = md.indexOf('\n---', 3)
    if (end !== -1) {
      const after = md.indexOf('\n', end + 1)
      return md.slice(after + 1).trim()
    }
  }
  return md.trim()
}

export function getSummary(slug: string): string | null {
  return bySlug[slug] ?? null
}

export function hasSummary(slug: string): boolean {
  return slug in bySlug
}
